### PR TITLE
New approach to nested fragments

### PR DESCRIPTION
**Pull request by glasseyes42**
So this isn't ready but figured best to get one open and get discussions flowing.

There is a bit of lovely recursion - the linter is not enjoying this (may have committed with a no-verify, the shame). There is also a failing test on limiting the depth right now as i've not worked that one out yet.

By creating a parxer instance on a fragment response and parsing the fresh content before responding back, this travels down and rides all the way back up the trees to provide a lovely nested collection of fragments.

### CODE REVIEW

**Comment by glasseyes42** [comment]
A note - right now this approach will likely incur at least the same performance penalty as before.

However, by proving it's possible to traverse the tree of imports via compoxure - we could do something as simple as on a services response of a fragment also add a special header indicating "I need parsing too". No header, no extra parse, and the content is just returned to the tag stream in parxer with no modifications. 

Still need to solve depth limiting. Tried again last night and opening this and failed.

**Comment by cliftonc** [comment]
Could we make it opt in?  e.g. if the parent fragment includes `cx-parse-again` (or something) it does it, otherwise it doesn't.

**Comment by glasseyes42** [comment]
So a parent could have a global switch - however it's like only one tree by tree basis that a parse is needed - and I'd think an app would know better than a parent that it would contain another fragment request.

**Comment by glasseyes42** [comment]
Likely. Damn phone

**Comment by cliftonc** [comment]
Agreed, cleaner and faster in a header from fragment to signal parsing again.

**Comment by glasseyes42** [comment]
- [ ] docs need updating

**Pull request merged**
