### PR TITLE
Test if the req.get exists

### LINKED ISSUE #73: White page when upgrading from 1.0.1 to 1.0.3 (and up)
I did an update from 1.0.1 to master and when I went to the site, I got a white page.
I also tried version 1.0.3 and it will also result in a white page.

The page gives a status 200, but the response is empty. 
I do not see any error that is causing this problem. I only see this in my terminal:
```
127.0.0.1 - - [20/Jun/2016:13:08:02 +0000] "GET /page/ HTTP/1.1" 200 - "http://www.mylocalsite.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36 FirePHP/4Chrome"
127.0.0.1 - - [20/Jun/2016:13:08:02 +0000] "GET /favicon.ico HTTP/1.1" 200 - "http://www.mylocalsite.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36 FirePHP/4Chrome"
```

> (changed my url to http://www.mylocalsite.com)

### PR DESCRIPTION
**Pull request by RonRademaker**
Closes #73 

I work with @man-andy on the same project, so I can confirm this fix works for our situation.

### CODE REVIEW

**Comment by gabceb** [comment]
Thanks for the PR @RonRademaker. Do you a specific test I could use to test this that repros w/o this fix? It would be great to understand what the issue is instead of only putting a guard statement since it may cause other unforseen consequences downstream

**Comment by RonRademaker** [comment]
I'll see if I can look into that, but I think I won't be able at least a week. Also, I don't have a situation where it works without the fix, which complicated tracing the exact cause.

**Comment by gabceb** [comment]
Thanks! Let me know when you can get the repro steps and we can take a close look. If you can see it in your code maybe you can just print the stack trace and `req` for this case and put it here?

**Comment by cliftonc** [comment]
I guess if you aren't using Express then req.get may not exist, given that using the headers to select a backend is very much optional behaviour this solution is fine by me.

**Pull request merged**
