### PR TITLE
Post template

### PR DESCRIPTION
**Pull request by bettiolo**
Adds support to POST a template string and see the rendered output

### CODE REVIEW

**Comment by skhoshoo** [comment]
:clap:

**Comment by gabceb** [comment]
Im ok with the change as long as there is config variable passed to enable this functionality or not that defaults to false. I don't know if we want to give folks out there the ability to POST to your live site and get the parsed response back

@bettiolo

**Comment by bettiolo** [comment]
@gabceb good point!

**Comment by bettiolo** [comment]
So, the additional commits to the PR make so that the POSTed template parsing code is behind a configuration setting which is going to be disabled by default. I need to spin another compoxure server with a different configuration but for some reason, it is failing on Travis

**Comment by gabceb** [comment]
Your tests are failing @bettiolo. Fix them, rebase and I'll merge and publish on npm

**Comment by bettiolo** [comment]
@gabceb fixed by https://github.com/tes/compoxure/commit/02e7d05b30763d99eadd8dfe48acdfe11d28ba0c

**Comment by gabceb** [comment]
Closed in favor of https://github.com/tes/compoxure/pull/56. Thanks @bettiolo

**Pull request closed without merging**
