### PR TITLE
tes/resources#2783 allow for backends with noCache to specify their o…

### PR DESCRIPTION
**Pull request by skhoshoo**
…wn flavor of the Cache-Control header -- tes/resources#2783

### CODE REVIEW

**Comment by gabceb** [comment]
Why not allow backends to set a headers property with header props and it respective values and override headers this way. By doing that you cover this case and we can stop adding random props to backends?

**Comment by skhoshoo** [comment]
Ok, maybe I can make the undocumented `passThroughHeaders` work for this case.

**Comment by gabceb** [comment]
More than happy to merge for the sake of debugging but I think we should revert once we are done and do it right

**Comment by skhoshoo** [comment]
Let me try with the other method first.

**Comment by cliftonc** [comment]
I'll document the passThroughHeaders, not sure why we didn't add to readme, but it should work in this case of copying the cache header through to the overall response.

**Pull request merged**
