### PR TITLE
Adding docker-compose as a more easy way to start the example

### PR DESCRIPTION
**Pull request by valentinvieriu**
As the example needs redis to run, I've created a docker-compose file that will take care of building up the env for the example.
Maybe in the future we can build real microservices that would simulate the real life situation where you do call different servers. Let me know if you are interested in simulating something like this

### CODE REVIEW

**Comment by cliftonc** [comment]
Nice idea - can you update the readme so it's also described there and I'll merge.  

I do think it's worthwhile building a more realistic and complex example, happy to bounce ideas around about what that might look like?

**Comment by gabceb** [comment]
Im on the more complex example side. It would be amazing if the example was of a blog site with a backend to serve the compoxure html and 2 real node services to serve the blog content and reviews. IMO it will give new users trying to wrap their head around this more things to interact and a setup that is closer to reality

Note that Im not saying that this PR should do so :)

**Comment by valentinvieriu** [comment]
@cliftonc The readme was already updated to reflect how should you start the app. Do you want a different format for that?

**Comment by valentinvieriu** [comment]
@gabceb I was thinking something it that direction too. But that more complex example might need it's own repo. I don't think we want to make the main repo to heavy.

**Comment by cliftonc** [comment]
Thanks - missed the readme update.

**Comment by cliftonc** [comment]
A more complex example would definitely be best as it's own repo, we could probably use our own internal implementation as a starting point @gabceb (e.g. service-page-composer), and add to it a few more services in sub-folders that can be `docker-compose up`'d.

**Comment by cliftonc** [comment]
Live with 1.0.11.

**Pull request merged**
