### PR TITLE
Added bundles as a separate plugin on parxer

### PR DESCRIPTION
**Pull request by gabceb**
Will leave here to not forget but DO NOT MERGE YET.

Depends on https://github.com/tes/parxer/pull/5/files and revert of https://github.com/tes/compoxure/commit/3b4dc7c904d5d1dedeedc61751dd0b1d445a4281

### CODE REVIEW

**Comment by gabceb** [comment]
I've tested with linked latest parxer code and tests are back to passing so keep calm and code on.... at midnight....

**Comment by cliftonc** [comment]
Haha - I'm not sure why I put the bundles in the same plugin as the url one - so it's good work to do.

**Comment by gabceb** [comment]
We are back to green. This is good to merge now

**Comment by cliftonc** [comment]
Manually merged.

**Pull request closed without merging**
